### ISSUE TITLE
www.watchtamiltv.com failed

### ISSUE THREAD

**Issue by nokia3660** [Gujal00/GujalKodiWork#26]
Hey dude, great work with DD, however getting an error for all VOD TV channel on APKLand Live TV. Kodi logs indicate a failure on www.watchtamiltv.com. Below is kodi log extract. Not sure if this is due to some issue in my end.

Appreciate your help.

20:50:15.383 T:860877568  NOTICE: URLResolver: Initializing URLResolver version: 4.0.17
20:50:16.372 T:860877568  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
20:50:27.025 T:860877568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.deccandelight/main.py", line 831, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.deccandelight/main.py", line 817, in router
                                                list_items(params['site'],params['iurl'])
                                              File "/home/osmc/.kodi/addons/plugin.video.deccandelight/main.py", line 566, in list_items
                                                movies,mode = cache.cacheFunction(scraper.get_items,iurl)
                                              File "/home/osmc/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/home/osmc/.kodi/addons/plugin.video.deccandelight/resources/scrapers/tamiltv.py", line 90, in get_items
                                                title = item['name']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
20:50:27.620 T:1925360128   ERROR: GetDirectory - Error getting plugin://plugin.video.deccandelight/?action=7&iurl=http%3a%2f%2fwww.watchtamiltv.com%2fchannels%2fget_vod.php%3ftag%3dtabone%26date%3d02%2f07%2f2018ZZZZSun%2520TV&site=tamiltv
20:50:27.621 T:1925360128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deccandelight/?action=7&iurl=http%3a%2f%2fwww.watchtamiltv.com%2fchannels%2fget_vod.php%3ftag%3dtabone%26date%3d02%2f07%2f2018ZZZZSun%2520TV&site=tamiltv) failed

**Comment by Gujal00** [comment]
The website is broken. Need to see if they fix. Can't do anything on the addon

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/c2608cc585849f25ddce0bb70a47af5be269331c
