### ISSUE TITLE
APK Land scrappers not working

### ISSUE THREAD

**Issue by kumarsiyer** [Gujal00/GujalKodiWork#35]

**Comment by Gujal00** [comment]
What is not working? Post the kodi log so that I can take a look.
If it is VOD section, yes it is broken on the website

**Comment by kumarsiyer** [comment]
Logs

```
15:28:29.544 T:123145334726656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/Users/xxxxx/Library/Application Support/Kodi/addons/plugin.video.deccandelight/main.py", line 861, in <module>
                                                router(sys.argv[2][1:])
                                              File "/Users/xxxxx/Library/Application Support/Kodi/addons/plugin.video.deccandelight/main.py", line 847, in router
                                                list_items(params['site'],params['iurl'])
                                              File "/Users/xxxxx/Library/Application Support/Kodi/addons/plugin.video.deccandelight/main.py", line 566, in list_items
                                                movies,mode = cache.cacheFunction(scraper.get_items,iurl)
                                              File "/Users/xxxxx/Library/Application Support/Kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/Users/xxxxx/Library/Application Support/Kodi/addons/plugin.video.deccandelight/resources/scrapers/tamiltv.py", line 90, in get_items
                                                title = item['name']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
15:28:29.816 T:140736195789696   ERROR: GetDirectory - Error getting plugin://plugin.video.deccandelight/?action=7&iurl=http%3a%2f%2fwww.watchtamiltv.com%2fchannels%2fget_vod.php%3ftag%3dtabtwo%26date%3d03%2f11%2f2018ZZZZVijay%2520TV&site=tamiltv
15:28:29.817 T:140736195789696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deccandelight/?action=7&iurl=http%3a%2f%2fwww.watchtamiltv.com%2fchannels%2fget_vod.php%3ftag%3dtabtwo%26date%3d03%2f11%2f2018ZZZZVijay%2520TV&site=tamiltv) failed
15:29:41.362 T:123145340628992 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
```

**Comment by Gujal00** [comment]
Yep, you are trying to access VOD which is broken on the apkland website. Can't do much yet

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/c2608cc585849f25ddce0bb70a47af5be269331c

**Comment by kumarsiyer** [comment]
Thanks man
